# Generated by Django 3.2.5 on 2022-05-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0062_alter_booking_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('building', models.CharField(max_length=200, null=True)),
                ('duplex', models.CharField(max_length=200, null=True)),
                ('number', models.CharField(max_length=200, null=True)),
                ('starting', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('building', models.CharField(max_length=200, null=True)),
                ('duplex', models.CharField(max_length=200, null=True)),
                ('number', models.CharField(max_length=200, null=True)),
                ('starting', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('building', models.CharField(max_length=200, null=True)),
                ('duplex', models.CharField(max_length=200, null=True)),
                ('number', models.CharField(max_length=200, null=True)),
                ('starting', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('building', models.CharField(max_length=200, null=True)),
                ('duplex', models.CharField(max_length=200, null=True)),
                ('number', models.CharField(max_length=200, null=True)),
                ('starting', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
