# Generated by Django 3.2.5 on 2022-05-09 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0063_booking1_booking2_booking3_booking4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='building',
        ),
        migrations.RemoveField(
            model_name='booking1',
            name='building',
        ),
        migrations.RemoveField(
            model_name='booking2',
            name='building',
        ),
        migrations.RemoveField(
            model_name='booking3',
            name='building',
        ),
        migrations.RemoveField(
            model_name='booking4',
            name='building',
        ),
    ]
