# Generated by Django 3.2.5 on 2022-05-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0064_auto_20220509_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('duplex', models.CharField(max_length=200, null=True)),
                ('number', models.CharField(max_length=200, null=True)),
                ('starting', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Booking1',
            new_name='Booking_1',
        ),
        migrations.RenameModel(
            old_name='Booking3',
            new_name='Booking_2',
        ),
        migrations.RenameModel(
            old_name='Booking2',
            new_name='Booking_3',
        ),
        migrations.DeleteModel(
            name='Booking4',
        ),
    ]
