# Generated by Django 3.2.5 on 2022-05-10 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0065_auto_20220510_1508'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking_3',
            new_name='Booking1',
        ),
        migrations.RenameModel(
            old_name='Booking_4',
            new_name='Booking2',
        ),
        migrations.RenameModel(
            old_name='Booking_1',
            new_name='Booking3',
        ),
        migrations.RenameModel(
            old_name='Booking_2',
            new_name='Booking4',
        ),
    ]
