# Generated by Django 3.2.5 on 2022-05-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0067_location1_location2_location3_location4_location5'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location1',
            old_name='starting',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='location2',
            old_name='starting',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='location3',
            old_name='starting',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='location4',
            old_name='starting',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='location5',
            old_name='starting',
            new_name='check_in',
        ),
        migrations.AddField(
            model_name='location1',
            name='check_out',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location2',
            name='check_out',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location3',
            name='check_out',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location4',
            name='check_out',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location5',
            name='check_out',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
