# Generated by Django 3.2.5 on 2023-02-23 12:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0069_news1_news2_news3_news4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='apts',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='building',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='category',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='location',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='name',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='property_price',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='temp',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='temp_cost',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='total_project_price',
        ),
        migrations.AddField(
            model_name='venue',
            name='Borrower_C',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='Investor_A',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='Investor_B',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='Project_D',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='request_form',
            field=models.FileField(default=datetime.datetime(2023, 2, 23, 12, 49, 29, 589324, tzinfo=utc), upload_to='request_forms/'),
            preserve_default=False,
        ),
    ]
