# Generated by Django 3.2.5 on 2023-02-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0070_auto_20230223_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='Borrower_C',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='Investor_A',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='Investor_B',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='Project_D',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
