# Generated by Django 3.2.5 on 2023-02-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0071_auto_20230223_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
