# Generated by Django 3.2.5 on 2023-08-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0073_auto_20230824_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking2',
            name='duplex',
        ),
        migrations.RemoveField(
            model_name='booking2',
            name='number',
        ),
        migrations.RemoveField(
            model_name='booking2',
            name='project',
        ),
        migrations.RemoveField(
            model_name='booking3',
            name='duplex',
        ),
        migrations.RemoveField(
            model_name='booking3',
            name='number',
        ),
        migrations.RemoveField(
            model_name='booking3',
            name='project',
        ),
        migrations.RemoveField(
            model_name='booking4',
            name='duplex',
        ),
        migrations.RemoveField(
            model_name='booking4',
            name='number',
        ),
        migrations.RemoveField(
            model_name='booking4',
            name='project',
        ),
        migrations.AddField(
            model_name='booking2',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking2',
            name='crowdfund',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking3',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking3',
            name='crowdfund',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking4',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking4',
            name='crowdfund',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
