# Generated by Django 3.2.5 on 2023-08-25 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0075_auto_20230825_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidity',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='co_servings.booking'),
        ),
    ]
