# Generated by Django 3.2.5 on 2023-08-26 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0076_alter_liquidity_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidity',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='liquidity',
            name='percent',
        ),
    ]
