# Generated by Django 3.2.5 on 2023-08-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0077_auto_20230826_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidity',
            name='booking',
            field=models.CharField(choices=[('Booking1', 'Booking1'), ('Booking2', 'Booking2'), ('Booking3', 'Booking3'), ('Booking4', 'Booking4')], max_length=200, null=True),
        ),
    ]
