# Generated by Django 3.2.5 on 2023-08-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0084_liquidity_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking1',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='booking2',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='booking3',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='booking4',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
