# Generated by Django 3.2.5 on 2023-08-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0087_payment1_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment1',
            name='booking',
        ),
        migrations.AddField(
            model_name='payment1',
            name='crowdfunding',
            field=models.CharField(choices=[('Crowdfunding1', 'Crowdfunding1'), ('Crowdfunding2', 'Crowdfunding2'), ('Crowdfunding3', 'Crowdfunding3'), ('Crowdfunding4', 'Crowdfunding4')], max_length=200, null=True),
        ),
    ]
