# Generated by Django 3.2.5 on 2023-08-28 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0088_auto_20230828_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidity',
            name='booking',
        ),
    ]
