# Generated by Django 3.2.5 on 2023-08-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co_servings', '0089_remove_liquidity_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment1',
            name='Design_Build_Project',
            field=models.CharField(choices=[('FBM-2', 'FBM-2'), ('FBM-3', 'FBM-3'), ('FBM-6', 'FBM-6'), ('FBM-10', 'FBM-10')], max_length=200, null=True),
        ),
    ]
